language: node_js
node_js:
- '4.0'
sudo: false
env:
  matrix:
  - GROUP=
  global:
  - GH_REF: github.com/jupyter/jupyter-js-ui.git
  - secure: ubVHruPyZKaY5IeG8VKjlIp0lTaAToNqWzLTzeT36GTz9DgCWvjRmbt4ZjezGToW4+eG2PT0OEDW5N7MBxmTxbOgdy4q6H98DsIeYLOFXaiggpWt5fpe8MWQcqIm3QIqzgJF4oEtMjAYvRFDgZHOq8ozChafjYB2Xt/G44in7cx7zp+AQwX5ACc9ku8N2x9Iyv7PtOl4Wb16ngQbLhJmNiX/x15lpA656Zwq2agPD5fdcu0w5fPbnkVXbCFDdSKbzrkyFvYDcbJUjE8lir+Eoj8rHwLpznMji6aunRaIXIeuNfRh2mxpZLdphlVJc+1KB69iPD40he21G/93gFrfee44H4jND+z07VFPt1QKBaPbdJxV40A6aJ8AtV1n8BvNjLEC+zTzGyhlIYcvb6c5Az70ERY+icz77zzBGesoXxRIGCmQSKcThhxuTicbJqpYcHQecvpuY9dCzeT8250FCkfeoFd9mxQaqyGjaJMLWnN/fsdDHmFuFD6BRlDMTgPYCfY9D8rMikd8D4WDEZKxx1AMPBDcKWXFvnaCmkYq0Of4ka8UUOZdX7MUC5JL6atGEMxPMyMoZqaGsIfFKhDH6LRuDKPSZMyNmTXGWBzcd3BZTXuw1W3CzM88zdTwoLjsEs6fcu1/rAwJllv/Ygq5CuaClC5BqEBmaYGOk4eVQDA=
install:
- bash ./scripts/travis_install.sh
script:
- bash ./scripts/travis_script.sh
after_success:
- bash ./scripts/travis_after_success.sh
